---
- name: Validate required variables are defined
  ansible.builtin.assert:
    that:
      - host_maindomain          is defined
      - authelia_subdomain       is defined
      - static_website_subdomain is defined
    fail_msg: "Required variable is not defined correctly for {{ inventory_hostname }}"
    quiet: true
  tags:
    - validate
