---
- name: Write caddy port mappings
  become: true
  become_user: "{{ caddy_user_name }}"
  ansible.builtin.template:
    src: port-mapping.conf.j2
    dest: port-mapping.conf
    mode: u=rw,g=r,o=
  notify: Schedule caddy restart
