---
- name: Finalize caddy setup
  block:
    - name: Create caddy port mappings
      ansible.builtin.import_tasks: 1-create-reverse-proxy-port-mappings.yaml

    - name: Render json caddy config
      ansible.builtin.import_tasks: 2-create-caddy-json-config.yaml

    - name: Restart caddy (if needed)
      ansible.builtin.import_tasks: 3-restart-caddy.yaml
