---
- name: Schedule caddy restart
  ansible.builtin.set_fact:
    _caddy_restart_needed: true

- name: Enable caddy
  become: true
  become_user: "{{ caddy_user_name }}"
  ansible.builtin.systemd_service:
    unit: "{{ caddy_service_unit }}"
    enabled: true
    scope: user
    daemon_reload: true
