---
opencloud_user_name: "opencloud"
opencloud_user_home: "/home/{{ opencloud_user_name }}"

opencloud_cloud_subdomain: "opencloud"
opencloud_cloud_port: "9200"

opencloud_version: "8.1"

opencloud_dir_data: "{{ opencloud_user_home }}/data"
opencloud_dir_config_opencloud: "{{ opencloud_user_home }}/config/opencloud"
