---
- name: Create opencloud quadlets
  become: true
  become_user: "{{ opencloud_user_name }}"
  block:

    - name: Create quadlet folder
      ansible.builtin.file:
        path: "{{ opencloud_user_home }}/.config/containers/systemd"
        state: directory
        mode: u=rwx,g=rx,o=

    - name: Create opencloud app container
      ansible.builtin.template:
        src: opencloud-server.container.j2
        dest: "{{ opencloud_user_home }}/.config/containers/systemd/opencloud-server.container"
        mode: u=rw,g=r,o=
      notify:
        - Restart opencloud

    - name: Create opencloud pod
      ansible.builtin.template:
        src: opencloud.pod.j2
        dest: "{{ opencloud_user_home }}/.config/containers/systemd/opencloud.pod"
        mode: u=rw,g=r,o=
      notify:
        - Restart opencloud

    - name: Enable opencloud
      ansible.builtin.systemd_service:
        unit: "opencloud-pod.service"
        scope: user
        enabled: true
        daemon_reload: true
