---
- name: Validate credential values are defined
  ansible.builtin.assert:
    that:
      - immich_database_password is defined
    fail_msg: "Required variable is not defined correctly for {{ inventory_hostname }}"
    quiet: true
  tags:
    - validate

- name: Create immich and postgres credentials
  become: true
  become_user: "{{ immich_user_name }}"
  block:
    - name: Create immich server credentials
      block:
        - name: Create immich server container dropin folder
          ansible.builtin.file:
            path: "{{ immich_server_container_d }}"
            state: directory
            mode: u=rwx,g=rx,o=

        - name: Create immich server credentials file
          block:
            - name: Check credential dropin exists
              ansible.builtin.stat:
                path: "{{ immich_server_container_d_credentials }}"
              register: immich_server_credentials_file
              diff: true

            - name: Create server credentials
              when: immich_refresh_credential or not immich_server_credentials_file.stat.exists
              block:
                - name: Generate credential database password
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ immich_database_password_name }} - -"
                    stdin: "{{ immich_database_password }}"
                  register: immich_server_database_password_cred
                  changed_when: false

                - name: Add systemd service credential dropin
                  ansible.builtin.copy:
                    dest: "{{ immich_server_container_d_credentials }}"
                    content: |
                      [Service]
                      {{ immich_server_database_password_cred.stdout }}
                    mode: u=rw,g=r,o=
                  notify:
                    - Restart immich

    - name: Create postgres credentials
      block:
        - name: Create immich postgres container dropin folder
          ansible.builtin.file:
            path: "{{ immich_postgres_container_d }}"
            state: directory
            mode: u=rwx,g=rx,o=

        - name: Create postgres credentials file
          block:
            - name: Check credentials dropin exists
              ansible.builtin.stat:
                path: "{{ immich_postgres_container_d_credentials }}"
              register: immich_postgres_credentials_file
              diff: true

            - name: Create postgres credentials
              when: immich_refresh_credential or not immich_postgres_credentials_file.stat.exists
              block:
                - name: Generate credential storage password
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ immich_database_password_name }} - -"
                    stdin: "{{ immich_database_password }}"
                  register: immich_postgres_database_password_cred
                  changed_when: false

                - name: Add systemd service credential dropin
                  ansible.builtin.copy:
                    dest: "{{ immich_postgres_container_d_credentials }}"
                    content: |
                      [Service]
                      {{ immich_postgres_database_password_cred.stdout }}
                    mode: u=rw,g=r,o=
                  notify:
                    - Restart immich
