---
- name: Add caddy integration
  become: true
  become_user: "{{ caddy_user_name }}"
  block:
    - name: Add caddy dropin configuration for immich with (optional) mTLS
      ansible.builtin.template:
        src: immich-mtls.caddy.j2
        dest: "{{ caddy_dir_caddyfile_subdomain_d }}/immich-mtls.caddy"
        mode: u=rw,g=r,o=

    - name: Add caddy pasta port mapping # noqa: var-naming
      ansible.builtin.set_fact:
        # add '-T,2283' to caddy's pasta parameters
        caddy_pasta_port_map: "{{ caddy_pasta_port_map | union(['-T,' ~ immich_port]) }}"
