---
- name: Pre-checks
  ansible.builtin.import_playbook: pre-checks.yaml

- name: Setup production
  hosts: all
  roles:
    - caddy
    - static_website
    - authelia
    - immich
    - opencloud

  post_tasks:
    - name: Finalize authelia setup
      ansible.builtin.include_role:
        name: authelia_finalization
      tags: always
    - name: Finalize caddy setup
      ansible.builtin.include_role:
        name: caddy_finalization
      tags: always
