---
- name: Validate required variables are defined
  ansible.builtin.assert:
    that:
      - authelia_user_name is defined
      - authelia_user_home is defined
    fail_msg: "Required variable is not defined correctly for {{ inventory_hostname }}"
    quiet: true
  tags:
    - validate

- name: Create authelia user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-service-user.yaml
  tags: always
  vars:
    common_user_name: "{{ authelia_user_name }}"
    common_user_home: "{{ authelia_user_home }}"
