---
- name: Create authelia and postgres credentials
  become: true
  become_user: "{{ authelia_user_name }}"
  block:

    - name: Create authelia app credentials
      block:

        - name: Create authelia app container dropin folder
          ansible.builtin.file:
            path: "{{ authelia_app_container_d }}"
            state: directory
            mode: u=rwx,g=rx,o=

        - name: Create authelia app credentials file
          block:

            - name: Check credential dropin exists
              ansible.builtin.stat:
                path: "{{ authelia_app_container_d_credentials }}"
              register: authelia_app_credentials_file
              diff: true

            - name: Create app credentials
              when: authelia_refresh_credential or not authelia_app_credentials_file.stat.exists
              block:
                - name: Generate credential smtp password
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_smtp_password_name }} - -"
                    stdin: "{{ authelia_smtp_password }}"
                  register: authelia_app_smtp_password_cred
                  changed_when: false

                - name: Generate credential storage encryption key
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_storage_encryption_key_name }} - -"
                    stdin: "{{ authelia_storage_encryption_key }}"
                  register: authelia_app_storage_encryption_key_cred
                  changed_when: false

                - name: Generate credential storage password
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_storage_password_name }} - -"
                    stdin: "{{ authelia_storage_password }}"
                  register: authelia_app_storage_password_cred
                  changed_when: false

                - name: Generate credential jwt secret
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_jwt_secret_name }} - -"
                    stdin: "{{ authelia_jwt_secret }}"
                  register: authelia_app_jwt_secret_cred
                  changed_when: false

                - name: Generate credential session secret
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_session_secret_name }} - -"
                    stdin: "{{ authelia_session_secret }}"
                  register: authelia_app_session_secret_cred
                  changed_when: false

                - name: Generate credential oidc hmac secret
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_oidc_hmac_secret_name }} - -"
                    stdin: "{{ authelia_oidc_hmac_secret }}"
                  register: authelia_app_oidc_hmac_secret_cred
                  changed_when: false

                - name: Load oidc private rsa key
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_oidc_jwk_key_name }} - -"
                    stdin: "{{ lookup('file', authelia_oidc_jwk_key_file) }}"
                  register: authelia_app_oidc_jwk_private_key_cred
                  changed_when: false

                - name: Add systemd service credential dropin
                  ansible.builtin.copy:
                    dest: "{{ authelia_app_container_d_credentials }}"
                    content: |
                      [Service]
                      {{ authelia_app_smtp_password_cred.stdout }}
                      {{ authelia_app_storage_encryption_key_cred.stdout }}
                      {{ authelia_app_storage_password_cred.stdout }}
                      {{ authelia_app_jwt_secret_cred.stdout }}
                      {{ authelia_app_session_secret_cred.stdout }}
                      {{ authelia_app_oidc_hmac_secret_cred.stdout }}
                      {{ authelia_app_oidc_jwk_private_key_cred.stdout }}
                    mode: u=rw,g=r,o=
                  notify:
                    - Restart authelia

    - name: Create postgres credentials
      block:

        - name: Create authelia postgres container dropin folder
          ansible.builtin.file:
            path: "{{ authelia_postgres_container_d }}"
            state: directory
            mode: u=rwx,g=rx,o=

        - name: Create postgres credentials file
          block:

            - name: Check credential dropin exists
              ansible.builtin.stat:
                path: "{{ authelia_postgres_container_d_credentials }}"
              register: authelia_postgres_credentials_file
              diff: true

            - name: Create postgres credentials
              when: authelia_refresh_credential or not authelia_postgres_credentials_file.stat.exists
              block:
                - name: Generate credential storage password
                  ansible.builtin.command:
                    cmd: "systemd-creds encrypt --user --pretty --name={{ authelia_storage_password_name }} - -"
                    stdin: "{{ authelia_storage_password }}"
                  register: authelia_postgres_storage_password_cred
                  changed_when: false

                - name: Add systemd service credential dropin
                  ansible.builtin.copy:
                    dest: "{{ authelia_postgres_container_d_credentials }}"
                    content: |
                      [Service]
                      {{ authelia_postgres_storage_password_cred.stdout }}
                    mode: u=rw,g=r,o=
                  notify:
                    - Restart authelia
