---
- name: Create caddy user
  ansible.builtin.include_role:
    name: common
    tasks_from: create-service-user.yaml
  tags: always
  vars:
    common_user_name: "{{ caddy_user_name }}"
    common_user_home: "{{ caddy_user_home }}"
